In [1]:
import numpy as np

arr = np.arange(12).reshape(3,4)

print('Original Array:')
print(arr)

print('Show the properties of the array:')
print(f'shape: {arr.shape}')
print(f'dtype:{arr.dtype}')
print(f'ndim:{arr.ndim}')

arr_deformed = arr.reshape(4,3)

print(arr)

print(arr_deformed) #reshape()不改变原数组的任何内容，只是返回新的视图
print(arr_deformed.shape)

arr_flattened = arr.flatten()
print(arr)
print(arr_flattened)

arr_ravel = arr.ravel()
print(arr)
print(arr_ravel)

arr_reshaped = arr.reshape(-1)
print(arr)
print(arr_reshaped)

arr_1 = arr.reshape(4,-1)
print(arr)
print(arr_1)
print(arr_1.shape)
print(arr.shape)

arr_2 = arr.reshape(-1,6)
print(arr_2)

arr_4 = np.arange(24)
print(arr_4)
arr_5 = arr_4.reshape(2,-1,3,2)
print(arr_5)
print(arr_5.shape)



Original Array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Show the properties of the array:
shape: (3, 4)
dtype:int64
ndim:2
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
(4, 3)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
